config/routes.rb
IrcSeedBank::Application.routes.draw do

  resources :dispensals do
		get 'list_seeds', :on => :collection 	
		get 'options', :on => :collection
	end

  resources :farmers 

  resources :donations do
		get 'list_seeds', :on => :collection 	
		get 'options', :on => :collection
	end

  resources :donors
  match '/seeds/add_quantity/:id' => 'seeds#add_quantity', as: :add_quantity
  resources :seeds	
	devise_for :users, :controllers => {:registrations => "registrations"}
	resources :users, :only => :show	
	authenticated :user do
	  root :to => 'home#index'
	end

	root :to => "home#index"

end

app/views/shared/_list.html.erb
<div class="apple_pagination">
		<%= will_paginate @objects %>		
		<ul>
			<% objects.each do |object| %>
				<li><%= link_to object.name, object %></li>
			<% end %>
		</ul>
</div>

app/views/shared/_navigation.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit account', edit_user_registration_path) %>
  </li>
	<li>
		<%= link_to('Seeds', seeds_path) %>
	</li>
	<li> 
		<%= link_to('Donors', donors_path) %>
	</li>
	<li>
		<%= link_to('Farmers', farmers_path) %>
	</li>
<% else %>

<% end %>

app/views/shared/_seed_list.html.erb
    <% @seeds.each do |seed| %>
      <br><%= radio_button_tag 'seed', seed.id, @seed == seed, {:checked => true} %>
      <%= seed.humanize %>
    <% end %>