config/routes.rb
IrcSeedBank::Application.routes.draw do

  resources :dispensals do
		get 'list_seeds', :on => :collection 	
		get 'options', :on => :collection
	end

  resources :farmers 

  resources :donations do
		get 'list_seeds', :on => :collection 	
		get 'options', :on => :collection
	end

  resources :donors
  match '/seeds/add_quantity/:id' => 'seeds#add_quantity', as: :add_quantity
  resources :seeds	
	devise_for :users, :controllers => {:registrations => "registrations"}
	resources :users, :only => :show	
	authenticated :user do
	  root :to => 'home#index'
	end

	root :to => "home#index"

end

app/models/donation.rb
class Donation < ActiveRecord::Base
	belongs_to :donor
	belongs_to :seed
	belongs_to :farmer
	before_destroy :update_seeds
	def pounds
		if(self.quantity < 1)
			return "#{(self.quantity * 28.3495).round.to_f} g"
		else
			return "#{self.quantity.floor / 16} lbs, #{((self.quantity % 16)*1000).round.to_f / 1000} oz"
		end
	end
	def ounces
		if(self.quantity < 1)
			return "#{(self.quantity * 28.3495).round.to_f} g"
		else
			return "#{((self.quantity % 16)*1000).round.to_f / 1000} oz"
		end
	end
	def update_seeds
		self.quantity = 0.0
		self.save
		self.seed.update_quantity
	end
	
	def date
		self.updated_at.strftime("%m/%d/%Y")
	end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_filter :authenticate_user!
	def options
		#setting final donation parameters before creation
		@seed = Seed.find(params[:seed])
		@donor = Donor.find(params[:donor_id])
		@donation = Donation.new
		@donation.donor = @donor
		@donation.seed = @seed
	end
	
	def list_seeds
		 @seeds = Seed.find_all_by_family(params[:seed_family])
	#list all seeds from family for selection
	   respond_to do |format|
     format.html # list_seeds.html.erb
     format.json { render json: @dispensals }
    end
	end
	
	# GET /donations
  # GET /donations.json
  def index

  end

  # GET /donations/1
  # GET /donations/1.json
  def show
    @donation = Donation.find(params[:id])
		if @donation.donor		
			@donor = @donation.donor
		end
		if @donation.farmer
			@donor = @donation.farmer
		end    
		respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/new
  # GET /donations/new.json
  def new
    @donation = Donation.new
		@donor = Donor.find(params[:donor_id])
		@donation.donor = @donor
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/1/edit
  def edit
    @donation = Donation.find(params[:id])
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(params[:donation])
		#set donation quantity
		

		@seed = Seed.find(params[:donation][:seed_id])
		@donation.seed = @seed
    
		respond_to do |format|
      if @donation.save
				#link seed to donation			
				@donation.update_attribute(:quantity, params[:grams].to_i*0.035274)			
				@donation.seed.update_quantity(@donation.quantity)
        format.html { redirect_to @seed, notice: 'Donation was successfully created.' }
        format.json { render json: @donation, status: :created, location: @donation }
      else
        format.html { render action: "options" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donations/1
  # PUT /donations/1.json
  def update
    @donation = Donation.find(params[:id])

    respond_to do |format|
      if @donation.update_attributes(params[:donation])
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @seed = Donation.find(params[:id]).seed
		Donation.destroy(params[:id])
		@seed.update_quantity
    respond_to do |format|
      format.html { redirect_to @seed }
      format.json { head :no_content }
    end
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.erb
<%= form_tag list_seeds_donations_path, :method => 'get' do %>
  <div class="field">
		<b>Family</b>
		<%= select_tag("seed_family", options_for_select(Seed.family_list, Seed.family_list)) %>
	</div>
	<div class="field">
		<%= hidden_field_tag 'donor_id', params[:donor_id] %>
	</div>
	<div class="field">
		<%= hidden_field_tag 'farmer_id', params[:farmer_id] %>
	</div>
  <div class="actions">
    <%= submit_tag "Find Seeds", :name => nil %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<div class="columnSingle">
You shouldn't be here.
</div>

app/views/donations/list_seeds.html.erb
<div class="article columnSingle">	
<%= form_tag options_donations_path, :method => 'get' do %>
	<div class="form_row">
    <label for="seeds">Choose Seed:</label>
		<%= render "shared/seed_list" %>
	</div>
	<div class="field">
		<%= hidden_field_tag 'donor_id', params[:donor_id] %>
	</div>
	 <div class="actions">
    <%= submit_tag "Select Seed", :name => nil %>
  </div>
<% end %>
</div>

app/views/donations/new.html.erb
<div class="article columnSingle">	
<h1>New Donation</h1>

<%= render 'form' %>

<%= link_to 'Back', donations_path %>
</div>

app/views/donations/options.html.erb
<div class="article columnSingle">	
<h3> Donation Information </h3>
<b>Seed Company: </b><%= @donor.name %><br />
<b>Seed: </b><%= @seed.humanize %><br />
<b>Current Quantity: </b><%= @seed.pounds %><br/>
<br />
<br />
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being processed:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class = "field">
		<b><%= f.label :quantity %>:</b>
		<%= text_field_tag :grams %>g
	</div>
	<div class = "field">
		<b><%= f.label :value %>:</b>
		<%= f.text_field :value %>$
	</div>
	<div class = "field">
		<b>Seed Year:</b>
		<%= f.text_field :seed_age %>
	</div>
	<div class = "field">
		<b>Is Donation</b>
		<%= f.check_box :is_donation %>
	</div>
	<div class="field">
		<%= f.hidden_field :donor_id %>
	</div>
	<div class="field">
		<%= hidden_field_tag 'farmer_id', params[:farmer_id] %>
	</div>
	<div class="field">
		<%= f.hidden_field :seed_id %>
	</div>
	<div class="field">
		<%= f.hidden_field :quantity, :value => 0 %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/donations/show.html.erb
<div id="feature">
	<p>
		<b>Seed:</b>
		<%= link_to @donation.seed.humanize, @donation.seed %>
	</p>
	<p>
		<b>Quantity:</b>
		<%= @donation.pounds %>
	</p>

	<p>
		<b>Value:</b>
		<% if @donation.value != nil %>
			$<%= format("%.2f", @donation.value) %>
		<% end %>	
	</p>

	<p> 
		<b>Seed Company:</b>
		<%= @donor.name %>
	</p>
	<div class="button">
		<%= button_to 'Delete Donation', @donation, confirm: 'Are you sure?', method: :delete %>
	</div>
</div>