config/routes.rb
IrcSeedBank::Application.routes.draw do

  resources :dispensals do
		get 'list_seeds', :on => :collection 	
		get 'options', :on => :collection
	end

  resources :farmers 

  resources :donations do
		get 'list_seeds', :on => :collection 	
		get 'options', :on => :collection
	end

  resources :donors
  match '/seeds/add_quantity/:id' => 'seeds#add_quantity', as: :add_quantity
  resources :seeds	
	devise_for :users, :controllers => {:registrations => "registrations"}
	resources :users, :only => :show	
	authenticated :user do
	  root :to => 'home#index'
	end

	root :to => "home#index"

end

app/models/seed.rb
class Seed < ActiveRecord::Base
	
	has_many :donations, :dependent => :destroy
	has_many :dispensals, :dependent => :destroy

	validates :family, :presence => true
	validates :variety, :presence => true
	validates_length_of :description, :in => 1..255, :allow_blank => true
	
	def pounds
		if(self.quantity < 1)
			return "#{(self.quantity * 28.3495).round.to_f} g"
		else
			return "#{self.quantity.floor / 16} lbs, #{((self.quantity % 16)*1000).round.to_f / 1000} oz"
		end
	end
	def ounces
		if(self.quantity < 1)
			return "#{(self.quantity * 28.3495).round.to_f} g"
		else
			return "#{((self.quantity % 16)*1000).round.to_f / 1000} oz"
		end
	end
	
	def total_value
		total = 0
		self.donations.each do |donation|
			total += (donation.value != nil ? donation.value : 0)
		end
		return total
	end
	
	def update_quantity(quantity)
		#get total quantity of seeds in bank based on 
		#donations and dispensals
		total = self.quantity + quantity
		update_attributes(:quantity => total)
	end
 
	def humanize
		"#{self.variety} #{self.family}"
	end

	def name
		self.humanize
	end

	def self.family_list
		#list all unique families
		@families = []
		Seed.all.each do |seed|
			@families << seed.family
			@families = @families.uniq
		end
		return @families
	end
	def self.search(variety, family)
		#find seeds based on variety and family 
		#or get all seeds
		if variety or family
			if !variety.empty? and !family.empty?
				find(:all, :conditions => ["variety = ? and family = ?", variety, family])
			elsif !variety.empty? and family.empty?
				find(:all, :conditions => ["variety = ?", variety])
			elsif !family.empty?
				find(:all, :conditions => ["family = ?", family])		
			end
		else
			find(:all)
		end 
	end
end

app/controllers/seeds_controller.rb
class SeedsController < ApplicationController

	before_filter :authenticate_user!

  # GET /seeds
  # GET /seeds.json
  def index
	if params[:seed_family]
		@seeds = Seed.find_all_by_family(params[:seed_family]).sort_by_variety.paginate(:page => params[:page], :order => 'variety, ASC', :per_page => 10, :remote => true)
	end
    respond_to do |format|
      format.html # index.html.erb
			format.js 
      format.json { render json: @seeds }
		end
  end

  # GET /seeds/1
  # GET /seeds/1.json
  def show
    @seed = Seed.find(params[:id])
		@dispensals = @seed.dispensals.all.paginate(:page => params[:page], :order => 'updated_at DESC', :per_page => 10)
		@donations = @seed.donations.all.paginate(:page => params[:page], :order => 'updated_at DESC', :per_page => 10)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @seed }
    end
  end

  # GET /seeds/new
  # GET /seeds/new.json
  def new
    @seed = Seed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @seed }
    end
  end

  # GET /seeds/1/edit
  def edit
    @seed = Seed.find(params[:id])
  end

  # POST /seeds
  # POST /seeds.json
  def create
    @seed = Seed.new(params[:seed])
		@seed.quantity = 0
    respond_to do |format|
      if @seed.save
        format.html { redirect_to @seed, notice: 'Seed was successfully created.' }
        format.json { render json: @seed, status: :created, location: @seed }
      else
        format.html { render action: "new" }
        format.json { render json: @seed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /seeds/1
  # PUT /seeds/1.json
  def update
    @seed = Seed.find(params[:id])

    respond_to do |format|
      if @seed.update_attributes(params[:seed])
        format.html { redirect_to @seed, notice: 'Seed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @seed.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_quantity
	@seed = Seed.find(params[:id])
	@ounces = params[:grams].to_i*0.035274
	@seed.update_quantity(@ounces)
    respond_to do |format|
	  if(request.method == "POST")
		format.html { redirect_to @seed, notice: 'Seed was successfully updated.' }
        format.json { head :no_content }
	  else
		  format.html
		  format.json { render json: @seed }
      end
    end
  end

  # DELETE /seeds/1
  # DELETE /seeds/1.json
  def destroy
    @seed = Seed.find(params[:id])
    @seed.destroy

    respond_to do |format|
      format.html { redirect_to seeds_url }
      format.json { head :no_content }
    end

  end
end

app/helpers/seeds_helper.rb
module SeedsHelper
end

app/views/seeds/_dispensal_list.html.erb
<div class="article column2">
	<h3> Dispensals </h3>
	<table>
		<tr>
			<th>Date</th>
		  <th>Farmer</th>
		  <th>Quantity</th>
		</tr>
	 <tr>
	<div class="apple_pagination">
		<%= will_paginate @dispensals %>
	</div>
		<% @dispensals.each do |dispensal| %>
			<td><%= dispensal.date %>
		  <td><%= link_to dispensal.farmer.name, dispensal.farmer %></td>
		  <td><%= dispensal.pounds %></td>
		  <td><%= link_to 'More Details', dispensal %></td>
		</tr>
	<% end %>
	</table>
</div>

app/views/seeds/_donor_list.html.erb
<div class="article column1">
	<h3> Donations </h3>
	<table>
		<tr>
			<th>Date</th>
			<th>Seed Company</th>
		  <th>Quantity</th>
		  <th>Value</th>

		</tr>
	<div class="apple_pagination">
		<%= will_paginate @donations %>
	</div>
	<% @donations.each do |donation| %>
		<tr>
			<td><%= donation.date %></td>
			<% if donation.donor %>	
		  	<td><%= link_to donation.donor.name, donation.donor %></td>
			<% end %>
			<% if donation.farmer %>	
		  	<td><%= link_to donation.farmer.name, donation.farmer %></td>
			<% end %>	  
			<td><%= donation.pounds %></td>
			<td>$<%= donation.value %></td>
		  <td><%= link_to 'More Details', donation %></td>
		</tr>
	<% end %>
	</table>
	
</div>

app/views/seeds/_form.html.erb
<%= form_for(@seed) do |f| %>
  <% if @seed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seed.errors.count, "error") %> prohibited this seed from being saved:</h2>

      <ul>
      <% @seed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :family %><br />
    <%= f.text_field :family %>
  </div>
  <div class="field">
    <%= f.label :variety %><br />
    <%= f.text_field :variety %>
  </div>
	  <div class="field">
    <%= f.label :spacing %>(inches)<br />
    <%= f.text_field :spacing %>
  </div>
  <div class="field">
    <%= f.label :maturity %>(weeks)<br />
    <%= f.text_field :maturity %>
  </div>
  <div class="field">
    <%= f.label :common_names %><br />
    <%= f.text_field :common_names %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => "43x10"  %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments, :size => "43x10"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seeds/_seeds.html.erb
<div class="apple_pagination">		
	<%= will_paginate %>		
		<table>
			<tr>
				<th>Seed</th>
					<th>Quantity</th>
			</tr>
			<% @seeds.each do |seed| %>
				<tr>
					<td><%= link_to seed.humanize, seed %></td>
					<td><%= seed.pounds %></td>  					</tr>
			<% end %>
		</table>
</div>

app/views/seeds/add_quantity.html.erb
<div class="article columnSingle">
	<%= form_tag("/seeds/add_quantity/" + @seed.id.to_s, method: "post") do %>
		<h1>Add Quantity To <%= @seed.humanize %></h1>

		<div class = "field">
			<b>Quantity:</b>
			<%= text_field_tag :grams %>g
		</div>
		<%= submit_tag("Add") %>
	<% end %>
</div>

app/views/seeds/edit.html.erb
<div class="article columnSingle">

<h1>Editing <%= @seed.humanize %></h1>
<td><%= button_to 'Delete Seed', @seed, confirm: 'Are you sure?', method: :delete %></td>
<%= render 'form' %>

</div>

app/views/seeds/index.html.erb
<div class="article columnSingle">	
	<div id="centeredContent">	
			<h1> Seeds</h1>
		<%= link_to 'New Seed', new_seed_path %>	
		<br />
		<br />

		<%= form_tag url_for(:controller => :seeds, :action => :index), :method => 'get', :remote => true do %>
			<b>Family: </b><%= select_tag("seed_family", options_for_select(Seed.family_list, Seed.family_list)) %>
			<%= submit_tag "Find Seeds", :name => nil %>
		<% end %>

		<div id="seed_list">
		</div>
	</div>
</div>

app/views/seeds/index.js.erb
$('#seed_list').html("<%=j render 'shared/list', :objects => @seeds %>");
$('.pagination a').attr('data-remote', 'true');

app/views/seeds/new.html.erb
<div class="article columnSingle">
	<div id="centeredContent">
		<h1>New Seed</h1>

		<%= render 'form' %>	
	</div>
</div>

app/views/seeds/show.html.erb
<div id="feature">
<p>
  <b>Seed:</b> 
	<%= @seed.humanize %>
</p>
<p>
  <b>Stock Quantity:</b>
  <%= @seed.pounds %>
</p>
<p>
  <b>Spacing:</b>
  <%= @seed.spacing %> inches
</p>
<p>
  <b>Maturity:</b>
  <%= @seed.maturity %> weeks
</p>
<p>
  <b>Common Names:</b>
  <%= @seed.common_names %>
</p>
<p>
	<b>Description:</b><br />
	<%= @seed.description %>
</p>
<p>
	<b>Comments</b><br />
	<%= @seed.comments %>
</p>
<p>
	<b>Total Value </b><br/>
	$<%= @seed.total_value %>
</p>
<%= link_to "Add Arbitrary Quantity", add_quantity_path(@seed) %>
<%= link_to "Edit Seed", edit_seed_path(@seed) %>
</div>
	<%= render "donor_list" %>
	<%= render "dispensal_list" %>