config/routes.rb
IrcSeedBank::Application.routes.draw do

  resources :dispensals do
		get 'list_seeds', :on => :collection 	
		get 'options', :on => :collection
	end

  resources :farmers 

  resources :donations do
		get 'list_seeds', :on => :collection 	
		get 'options', :on => :collection
	end

  resources :donors
  match '/seeds/add_quantity/:id' => 'seeds#add_quantity', as: :add_quantity
  resources :seeds	
	devise_for :users, :controllers => {:registrations => "registrations"}
	resources :users, :only => :show	
	authenticated :user do
	  root :to => 'home#index'
	end

	root :to => "home#index"

end

app/models/dispensal.rb
class Dispensal < ActiveRecord::Base
	belongs_to :seed
	belongs_to :farmer
	before_destroy :update_seeds
	def pounds
		if(self.quantity < 1)
			return "#{(self.quantity * 28.3495).round.to_f} g"
		else
			return "#{self.quantity.floor / 16} lbs, #{((self.quantity % 16)*1000).round.to_f / 1000} oz"
		end
	end
	def ounces
		if(self.quantity < 1)
			return "#{(self.quantity * 28.3495).round.to_f} g"
		else
			return "#{((self.quantity % 16)*1000).round.to_f / 1000} oz"
		end
	end
	def update_seeds
		self.quantity = 0.0
		self.save
		self.seed.update_quantity
	end

	def date
		self.updated_at.strftime("%m/%d/%Y")
	end
end

app/controllers/dispensals_controller.rb
class DispensalsController < ApplicationController
	before_filter :authenticate_user!
	def options
		#setting final dispensal parameters before creation
		@seed = Seed.find(params[:seed])
		@farmer = Farmer.find(params[:farmer_id])
		@dispensal = Dispensal.new
		@dispensal.farmer = @farmer
		@dispensal.seed = @seed
	end
	
	def list_seeds
		 @seeds = Seed.find_all_by_family(params[:seed_family])
	#list all seeds from family for selection
	   respond_to do |format|
     format.html # list_seeds.html.erb
     format.json { render json: @dispensals }
    end
	end

  # GET /dispensals
  # GET /dispensals.json
  def index

  end

  # GET /dispensals/1
  # GET /dispensals/1.json
  def show
    @dispensal = Dispensal.find(params[:id])
		@farmer = @dispensal.farmer
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dispensal }
    end
  end

  # GET /dispensals/new
  # GET /dispensals/new.json
  def new
    @dispensal = Dispensal.new
		@farmer = Farmer.find(params[:farmer_id])
		@dispensal.farmer = @farmer
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dispensal }
    end
  end

  # POST /dispensals
  # POST /dispensals.json
  def create
    @dispensal = Dispensal.new(params[:dispensal])
		@seed = Seed.find(params[:dispensal][:seed_id])
		@dispensal.seed = @seed
		@farmer = @dispensal.farmer
    respond_to do |format|
				@dispensal.update_attribute(:quantity, params[:grams].to_i*0.035274)	
			if @dispensal.quantity > @seed.quantity
			 redirect_to(options_dispensals_path( :seed => params[:dispensal][:seed_id], :farmer_id => @farmer.id), alert: 'Not enough seeds.') and return false
			end
      if @dispensal.save
		
		@dispensal.seed.update_quantity(@dispensal.quantity)
        format.html { redirect_to @farmer, notice: 'Dispensal was successfully created.' }
        format.json { render json: @dispensal, status: :created, location: @dispensal }
      else
        format.html { render action: "options" }	
        format.json { render json: @dispensal.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /dispensals/1/edit
  def edit
    @dispensal = Dispensal.find(params[:id])
  end

  # PUT /dispensals/1
  # PUT /dispensals/1.json
  def update
    @dispensal = Dispensal.find(params[:id])

    respond_to do |format|
      if @dispensal.update_attributes(params[:dispensal])
        format.html { redirect_to @dispensal, notice: 'Dispensal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dispensal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dispensals/1
  # DELETE /dispensals/1.json
  def destroy
    @dispensal = Dispensal.find(params[:id])
    @dispensal.destroy
		@seed = @dispensal.seed
		@seed.update_quantity
    respond_to do |format|
      format.html { redirect_to dispensals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dispensals_helper.rb
module DispensalsHelper
end

app/views/dispensals/_form.html.erb
<%= form_tag list_seeds_dispensals_path, :method => 'get' do %>
  <div class="field">
		<b>Family</b>
		<%= select_tag("seed_family", options_for_select(Seed.family_list, Seed.family_list)) %>
	</div>
	<div class="field">
		<%= hidden_field_tag 'farmer_id', params[:farmer_id] %>
	</div>
  <div class="actions">
    <%= submit_tag "Find Seeds", :name => nil %>
  </div>
<% end %>

app/views/dispensals/edit.html.erb
<h1>Editing dispensal</h1>

<div class="article columnSingle">
	<h3> Dispensal Information </h3>
	<b>Farmer: </b><%= @dispensal.farmer.name %><br />
	<b>Seed: </b><%= @dispensal.seed.humanize %><br />
	<b>Quantity: </b><%= @dispensal.seed.pounds %><br/>
	<br />
	<br />
	<%= form_for(@dispensal) do |f| %>
		<% if @dispensal.errors.any? %>
		  <div id="error_explanation">
		    <h2><%= pluralize(@dispensal.errors.count, "error") %> prohibited this dispensal from being processed:</h2>

		    <ul>
		    <% @dispensal.errors.full_messages.each do |msg| %>
		      <li><%= msg %></li>
		    <% end %>
		    </ul>
		  </div>
		<% end %>
		<div class = "field">
			<b><%= f.label :planting_date %>:</b>
			<%= f.text_field :planting_date, :class => "datepicker" %>
		</div>
		<div class = "field">
			<b><%= f.label :harvest_date %>:</b>
			<%= f.text_field :harvest_date, :class => "datepicker" %>
		</div>
		<div class = "field">
			<b><%= f.label :soil_test_zone %>:</b>
			<%= f.text_field :soil_test_zone %>
		</div>
		<div class = "field">
			<b><%= f.label :row_feet %>:</b>
			<%= f.text_field :row_feet %>ft
		</div>
		<div class = "field">
			<b><%= f.label :germination_rate %>:</b>
			<%= f.text_field :germination_rate %>%
		</div>
		<div class = "field">
			<b><%= f.label :water_usage %>:</b>
			<%= f.text_field :water_usage %>ft^3
		</div>
	  <div class="field">
		<%= f.label :tissue_samples %><br />
		<%= f.text_area :tissue_samples, :size => "43x10"  %>
	  </div>

	  <div class="field">
		<%= f.label :comments %><br />
		<%= f.text_area :comments, :size => "43x10"  %>
	  </div>
		<div class="field">
			<%= f.hidden_field :farmer_id %>
		</div>
		<div class="field">
			<%= f.hidden_field :seed_id %>
		</div>
		<div class="actions">
		  <%= f.submit %>
		</div>
	<% end %>
</div>


<%= link_to 'Back', @dispensal %> 

app/views/dispensals/index.html.erb
<div class="columnSingle">
You shouldn't be here.
</div>

app/views/dispensals/list_seeds.html.erb
<div class="article columnSingle">
	<%= form_tag options_dispensals_path, :method => 'get' do %>
		<div class="form_row">
		  <label for="seeds">Choose Seed:</label>
			<%= render "shared/seed_list" %>
		</div>
		<div class="field">
			<%= hidden_field_tag 'farmer_id', params[:farmer_id] %>
		</div>
		 <div class="actions">
		  <%= submit_tag "Select Seed", :name => nil %>
		</div>
	<% end %>
</div>

app/views/dispensals/new.html.erb
<h1>New dispensal</h1>

<%= render 'form' %>

<%= link_to 'Back', dispensals_path %>

app/views/dispensals/options.html.erb
<div class="article columnSingle">
	<h3> Dispensal Information </h3>
	<b>Farmer: </b><%= @farmer.name %><br />
	<b>Seed: </b><%= @seed.humanize %><br />
	<b>Quantity: </b><%= @seed.pounds %><br/>
	<br />
	<br />
	<%= form_for(@dispensal) do |f| %>
		<% if @dispensal.errors.any? %>
		  <div id="error_explanation">
		    <h2><%= pluralize(@dispensal.errors.count, "error") %> prohibited this dispensal from being processed:</h2>

		    <ul>
		    <% @dispensal.errors.full_messages.each do |msg| %>
		      <li><%= msg %></li>
		    <% end %>
		    </ul>
		  </div>
		<% end %>
		<div class = "field">
			<b><%= f.label :quantity %>:</b>
			<%= text_field_tag :grams %>g
		</div>
		<div class = "field">
			<b><%= f.label :planting_date %>:</b>
			<%= f.text_field :planting_date, nil, :class => "datepicker" %>
		</div>
		<div class = "field">
			<b><%= f.label :harvest_date %>:</b>
			<%= f.text_field :harvest_date, nil, :class => "datepicker" %>
		</div>
		<div class = "field">
			<b><%= f.label :soil_test_zone %>:</b>
			<%= f.text_field :soil_test_zone %>
		</div>
		<div class = "field">
			<b><%= f.label :row_feet %>:</b>
			<%= f.text_field :row_feet %>ft
		</div>
		<div class = "field">
			<b><%= f.label :germination_rate %>:</b>
			<%= f.text_field :germination_rate %>%
		</div>
		<div class = "field">
			<b><%= f.label :water_usage %>:</b>
			<%= f.text_field :water_usage %>ft^3
		</div>
	  <div class="field">
		<%= f.label :tissue_samples %><br />
		<%= f.text_area :tissue_samples, :size => "43x10"  %>
	  </div>

	  <div class="field">
		<%= f.label :comments %><br />
		<%= f.text_area :comments, :size => "43x10"  %>
	  </div>
		<div class="field">
			<%= f.hidden_field :farmer_id %>
		</div>
		<div class="field">
			<%= f.hidden_field :seed_id %>
		</div>
		<div class="actions">
		  <%= f.submit %>
		</div>
	<% end %>
</div>

app/views/dispensals/show.html.erb
<div id="feature">
	<p>
		<b>Seed:</b>
		<%= link_to @dispensal.seed.humanize, @dispensal.seed %>
	<p>
		<b>Quantity:</b>
		<%= @dispensal.pounds %>
	</p>
	<p> 
		<b>Farmer:</b>
		<%= link_to @farmer.name, @farmer %>
	</p>
	<p>
		<b>Planting Date:</b>
		<%= @dispensal.planting_date %>
	</p>
	<p>
		<b>Harvest Date:</b>
		<%= @dispensal.harvest_date %>
	</p>
	<p>
		<b>Soil Test Zone:</b>
		<%= @dispensal.soil_test_zone %>
	</p>
	<p>
		<b>Row Feet:</b>
		<%= @dispensal.row_feet %> ft
	</p>
	<p>
		<b>Germination Rate:</b>
		<%= @dispensal.germination_rate %> %
	</p>	
	<p>
		<b>Water Usage:</b>
		<%= @dispensal.water_usage %> ft^3
	</p>
	<p>
		<b>Tissue Samples:</b>
		<%= @dispensal.tissue_samples %>
	</p>
	<p>
		<b>Comments:</b>
		<%= @dispensal.comments %>
	</p>	
	<div class="button">
		<%= link_to "Edit Dispensal", edit_dispensal_path(@dispensal) %>
	</div>
	<div class="button">
		<%= button_to 'Delete Dispensal', @dispensal, confirm: 'Are you sure?', method: :delete %>
	</div>
</div>